### ISSUE TITLE
umi-block.json 275 行多了个 null

### ISSUE THREAD

**Issue by hzyhbk** [ant-design/ant-design-blocks#3]
https://github.com/ant-design/ant-design-blocks/blob/master/umi-block.json#L275

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-blocks/pull/4

https://github.com/ant-design/ant-design-blocks/blob/092b9ca9621a8563ee24a60c2baeefdd99b7f466/src/index.js#L148
